joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

wheel1_controller:
    type: velocity_controllers/JointVelocityController
    joint: rim_wheel1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

wheel2_controller:
    type: velocity_controllers/JointVelocityController
    joint: rim_wheel2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

wheel3_controller:
    type: effort_controllers/JointPositionController
    joint: rim_wheel3_joint
    pid: {p: 40.0, i: 0.0, d: 1.0}

wheel4_controller:
    type: effort_controllers/JointPositionController
    joint: rim_wheel4_joint
    pid: {p: 40.0, i: 0.0, d: 1.0}
